#!/usr/bin/env php
<?php

require_once __DIR__.'/../app/bootstrap/autoload.php';
$app = require_once __DIR__.'/../app/bootstrap/app.php';

// Prepare the command line
$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);

$status = $kernel->handle(
    $input = new Symfony\Component\Console\Input\ArgvInput,
    new Symfony\Component\Console\Output\ConsoleOutput
);

$kernel->terminate($input, $status);

exit($status);
