#!/bin/bash
# Compile a PHP that works fine with BIRD3.
# This currently contains Apple's default parameters.

./configure
'--program-prefix=bird3-' \
'--enable-cli' \
'--disable-cgi' \
'--with-openssl=/usr' \
'--with-zlib=/usr' \
'--with-bz2=/usr' \
'--with-curl' \
'--with-ndbm' \
'--enable-exif' \
'--enable-ftp' \
'--with-gd' \
'--enable-gd-native-ttf' \
'--with-libedit' \
'--enable-mbstring' \
'--enable-mbregex' \
'--with-mysql=mysqlnd' \
'--with-mysqli=mysqlnd' \
'--with-pear' \
'--with-pdo-mysql=mysqlnd' \
'--with-mysql-sock' \
'--with-readline' \
'--enable-sockets' \
'--enable-sysvmsg' \
'--enable-sysvsem' \
'--enable-sysvshm' \
'--with-iconv' \
'--with-xsl' \
'--enable-zend-multibyte' \
'--enable-zip' \
'--with-pcre-regex' \
'--enable-debug' \
$*
